---
- name: Create changelog configuration entry
  ldap_entry:
    params: "{{ ldap_auth }}"
    dn: "cn=changelog5,cn=config"
    objectClass:
      - top
      - extensibleObject
    attributes:
      cn: "changelog5"
      # Fails if this is not set, although it's not a MUST attribute
      # (but there's dark magic taking place with extensibleObject)
      nsslapd-changelogdir: "/var/lib/dirsrv/slapd-{{ serverid }}/changelogdb"
    state: present

- name: Configure changelog
  ldap_attr:
    params: "{{ ldap_auth }}"
    dn: "cn=changelog5,cn=config"
    name: "{{ item.name }}"
    values: "{{ item.value }}"
    state: exact
  loop:
  - { name: "nsslapd-changelogdir", value: "/var/lib/dirsrv/slapd-{{ serverid }}/changelogdb" }
  - { name: "nsslapd-changelogmaxage", value: "10d" } # TODO: make configurable
