---
- set_fact:
    instance_389ds_is_consumer: replica_role == 'consumer' or replica_role == 'both'
    instance_389ds_is_supplier: replica_role == 'supplier' or replica_role == 'both'

- assert:
    that:
      - instance_389ds_is_consumer or instance_389ds_is_supplier
    msg: "This server is neither a consumer nor a supplier. Check that \"replica_role\" is set correctly."

- name: Prepare LDAP auth data
  set_fact:
    ldap_auth:
      server_uri: "{{ server_uri }}"
      validate_certs: "{{ tls_certificate_public_trusted }}"
      start_tls: "{{ use_starttls }}"
      bind_dn: "{{ rootdn }}"
      bind_pw: "{{ rootdn_password }}"

# There are 3 possible configurations:
# Supplier ONLY: is configured as a supplier, with a replication agreement and no replication user.
# Consumer ONLY: is configured as a consumer, with no replication agreement but a replication user.
# Supplier + consumer (master/both): is configured as a supplier, with a replication agreement and a replication user.

# Supplier or master/both
- include: configure_changelog.yml
  when: instance_389ds_is_supplier

# Consumer or master/both
- include: configure_replication_user.yml
  when: instance_389ds_is_consumer

# Consumer
- include: configure_consumer.yml
  when: instance_389ds_is_consumer and not instance_389ds_is_supplier

# Supplier or master/both
- include: configure_supplier.yml
  when: instance_389ds_is_supplier

# Supplier or master/both
- include: configure_replication_agreement.yml
  when: instance_389ds_is_supplier
