---
- name: Prepare LDAP auth data
  set_fact:
    ldap_auth:
      server_uri: "{{ server_uri }}"
      validate_certs: "{{ tls_certificate_public_trusted }}"
      start_tls: "{{ use_starttls }}"
      bind_dn: "{{ rootdn }}"
      bind_pw: "{{ rootdn_password }}"

- include: configure_supplier.yaml
  when: supplier

- include: configure_consumer.yaml
  when: consumer

- include: configure_replication_agreement.yaml
  when: TODO
